In [2]:
import pandas as pd

In [3]:
print("Pandas version:", pd.__version__)

Pandas version: 3.0.5


In [6]:
s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [8]:
s = pd.Series([1, 3, 5, None, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [10]:
s = pd.Series([1,2,3],index=['a','b','c'])
s

a    1
b    2
c    3
dtype: int64

In [13]:
s['a']

np.int64(1)

In [14]:
s.values

array([1, 2, 3])

In [15]:
s.index

Index(['a', 'b', 'c'], dtype='str')

In [17]:
s.dtype

dtype('int64')

In [20]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6,  2.4, 2.9]}
dataframe = pd.DataFrame(data)
dataframe

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [21]:
dataframe.shape

(5, 3)

In [24]:
dataframe.head(2)

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7


In [25]:
dataframe.tail(2)

,state,year,pop
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [26]:
len(dataframe)

5

In [28]:
df = pd.DataFrame([[1, 2], [3, 4]], index=['a', 'b'], columns=['one', 'two'])
df

,one,two
a,1,2
b,3,4


In [34]:
data = { "Name": ["Sanjay", "Nicey", "Janu", "Manu", "Aarav"], "Age": [24, 22, 25, 28, 24], "City": ["Hyderabad", "Hyderabad", "Hyderabad", "Hyderabad", "Delhi"], "Salary": [90000, 80000, 80000, 80000, 60000] }
data = pd.DataFrame(data)
data

,Name,Age,City,Salary
0,Sanjay,24,Hyderabad,90000
1,Nicey,22,Hyderabad,80000
2,Janu,25,Hyderabad,80000
3,Manu,28,Hyderabad,80000
4,Aarav,24,Delhi,60000


In [36]:
data["Name"]

0    Sanjay
1     Nicey
2      Janu
3      Manu
4     Aarav
Name: Name, dtype: str

In [39]:
data.loc[0:1,["Name", "Salary"]]

,Name,Salary
0,Sanjay,90000
1,Nicey,80000


In [46]:
data.loc[0:2]

,Name,Age,City,Salary
0,Sanjay,24,Hyderabad,90000
1,Nicey,22,Hyderabad,80000
2,Janu,25,Hyderabad,80000


In [47]:
data.iloc[0:2]

,Name,Age,City,Salary
0,Sanjay,24,Hyderabad,90000
1,Nicey,22,Hyderabad,80000


In [49]:
data.iloc[0:3,0:2]

,Name,Age
0,Sanjay,24
1,Nicey,22
2,Janu,25


In [51]:
data[data["Age"] >= 24]

,Name,Age,City,Salary
0,Sanjay,24,Hyderabad,90000
2,Janu,25,Hyderabad,80000
3,Manu,28,Hyderabad,80000
4,Aarav,24,Delhi,60000


In [55]:
data.sort_values(by="Age", ascending=True)

,Name,Age,City,Salary
1,Nicey,22,Hyderabad,80000
0,Sanjay,24,Hyderabad,90000
4,Aarav,24,Delhi,60000
2,Janu,25,Hyderabad,80000
3,Manu,28,Hyderabad,80000


In [56]:
data["Age"].unique()

array([24, 22, 25, 28])

In [62]:
data["City"].value_counts()

City
Hyderabad    4
Delhi        1
Name: count, dtype: int64

In [63]:
data.nlargest(3, "Salary")

,Name,Age,City,Salary
0,Sanjay,24,Hyderabad,90000
1,Nicey,22,Hyderabad,80000
2,Janu,25,Hyderabad,80000


In [64]:
data.nsmallest(3, "Salary")

,Name,Age,City,Salary
4,Aarav,24,Delhi,60000
1,Nicey,22,Hyderabad,80000
2,Janu,25,Hyderabad,80000


In [69]:
data["Salary"].isnull().sum()

np.int64(0)

In [70]:
data["Salary"].describe()

count        5.00000
mean     78000.00000
std      10954.45115
min      60000.00000
25%      80000.00000
50%      80000.00000
75%      80000.00000
max      90000.00000
Name: Salary, dtype: float64

In [88]:
import pandas as pd
import numpy as np 
data = { "Name": ["Sanjay", "Rahul", "Rahul", "Priya", "Ankit"], "Age": [24, np.nan, np.nan, 25, 28], "City": ["Hyderabad", "Delhi", "Delhi", " Mumbai ", "bangalore"], "Salary": [50000, 40000, 40000, np.nan, 80000] } 
df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [89]:
df.isnull()

,Name,Age,City,Salary
0,False,False,False,False
1,False,True,False,False
2,False,True,False,False
3,False,False,False,True
4,False,False,False,False


In [90]:
df.isnull().sum().sum()

np.int64(3)

In [91]:
df.isnull().values.any()

np.True_

In [92]:
df.dropna()

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
4,Ankit,28.0,bangalore,80000.0


In [93]:
df

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [94]:
df.ffill()

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,24.0,Delhi,40000.0
2,Rahul,24.0,Delhi,40000.0
3,Priya,25.0,Mumbai,40000.0
4,Ankit,28.0,bangalore,80000.0


In [95]:
df.drop_duplicates(subset=["Name"])

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [96]:
df

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [97]:
df.rename(columns={"Name":"Names"})

,Names,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [98]:
df

,Name,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [102]:
df.columns = ["Names", "Age", "City", "Salary"]

In [103]:
df

,Names,Age,City,Salary
0,Sanjay,24.0,Hyderabad,50000.0
1,Rahul,NaN,Delhi,40000.0
2,Rahul,NaN,Delhi,40000.0
3,Priya,25.0,Mumbai,NaN
4,Ankit,28.0,bangalore,80000.0


In [105]:
df["Email"] = ["sanjay@example.com", "rahul@example.com","rahul@example.com","priya@example.com ", "ankit@example.com"]

In [106]:
df

,Names,Age,City,Salary,Email
0,Sanjay,24.0,Hyderabad,50000.0,sanjay@example.com
1,Rahul,NaN,Delhi,40000.0,rahul@example.com
2,Rahul,NaN,Delhi,40000.0,rahul@example.com
3,Priya,25.0,Mumbai,NaN,priya@example.com
4,Ankit,28.0,bangalore,80000.0,ankit@example.com


In [107]:
df["Email"].str.split("@")

0    [sanjay, example.com]
1     [rahul, example.com]
2     [rahul, example.com]
3    [priya, example.com ]
4     [ankit, example.com]
Name: Email, dtype: object

In [110]:
df["Double Salary"] = df["Salary"].apply(lambda x:x*2)
df

,Names,Age,City,Salary,Email,Double Salary
0,Sanjay,24.0,Hyderabad,50000.0,sanjay@example.com,100000.0
1,Rahul,NaN,Delhi,40000.0,rahul@example.com,80000.0
2,Rahul,NaN,Delhi,40000.0,rahul@example.com,80000.0
3,Priya,25.0,Mumbai,NaN,priya@example.com,NaN
4,Ankit,28.0,bangalore,80000.0,ankit@example.com,160000.0


In [121]:
import pandas as pd

employees = pd.DataFrame({
    "EmployeeID":[1,2,3,4],
    "Name":["Sanjay","Rahul","Priya", "Amit"],
    "DepartmentID":[101,102,101,99]
})


departments = pd.DataFrame({
    "DepartmentID":[101,102],
    "Department":["AI","Cloud"]
})

In [122]:
concatenated_df = pd.concat([employees, departments],axis=0)
concatenated_df

,EmployeeID,Name,DepartmentID,Department
0,1.0,Sanjay,101,NaN
1,2.0,Rahul,102,NaN
2,3.0,Priya,101,NaN
3,4.0,Amit,99,NaN
0,NaN,NaN,101,AI
1,NaN,NaN,102,Cloud


In [125]:
merged_df = pd.merge(employees, departments, on="DepartmentID",how="inner")
merged_df

,EmployeeID,Name,DepartmentID,Department
0,1,Sanjay,101,AI
1,2,Rahul,102,Cloud
2,3,Priya,101,AI


In [126]:
pd.merge(employees, departments, on="DepartmentID", how="left")

,EmployeeID,Name,DepartmentID,Department
0,1,Sanjay,101,AI
1,2,Rahul,102,Cloud
2,3,Priya,101,AI
3,4,Amit,99,NaN


In [127]:
pd.merge(employees, departments, on="DepartmentID", how="right")

,EmployeeID,Name,DepartmentID,Department
0,1,Sanjay,101,AI
1,3,Priya,101,AI
2,2,Rahul,102,Cloud


In [129]:
pd.merge(employees, departments, on="DepartmentID", how="outer")

,EmployeeID,Name,DepartmentID,Department
0,4,Amit,99,NaN
1,1,Sanjay,101,AI
2,3,Priya,101,AI
3,2,Rahul,102,Cloud


In [136]:
pd.Timestamp.today(tz="Asia/Kolkata")

Timestamp('2026-09-13 20:02:57.757796+0530', tz='Asia/Kolkata')

In [145]:
import pandas as pd
users = [ { "Name": "Sanjay", "Age": 24, "City": "Hyderabad" }, { "Name": "Rahul", "Age": 22, "City": "Delhi" } ]
df = pd.DataFrame(users)

df.to_json("output.json", orient="records") #We have multiple orient options available for orient parameter. The default is 'columns', which will create a JSON object with column names as keys and lists of column values as values. The 'records' option will create a list of dictionaries, where each dictionary represents a row in the DataFrame.

In [146]:
data = { "Department": "AI", "Employees": [ {"Name": "Sanjay"}, {"Name": "Rahul"} ] }

In [149]:
pd.json_normalize(data,record_path="Employees",meta=["Department"])

,Name,Department
0,Sanjay,AI
1,Rahul,AI


In [150]:
import numpy as np
import time

python_list = list(range(1_000_000))
numpy_array = np.arange(1_000_000)

start = time.time()
python_result = [x * 2 for x in python_list]
print(f"Python list: {time.time() - start:.4f}s")

start = time.time()
numpy_result = numpy_array * 2
print(f"NumPy array: {time.time() - start:.4f}s")

Python list: 0.0568s
NumPy array: 0.0033s


In [154]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
col = np.array([[10], [20], [30]])   # shape (3, 1)
matrix + col

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [165]:
import time

df = pd.DataFrame({"text": ["hello world"] * 100_000})

start = time.time()
df["text"].apply(len)              # disguised loop
print(f"apply: {time.time() - start:.4f}s")

start = time.time()
df["text"].str.len()                # vectorized
print(f"str.len: {time.time() - start:.4f}s")

apply: 0.0246s
str.len: 0.0090s
