## Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(3,)

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [8]:
arr.ndim

2

In [9]:
arr3 = np.array([
    [
        [1,2,9],
        [3,4,9]
    ],
    [
        [5,6,9],
        [7,8,9]
    ]
])  # 3D array , Height, Width, Depth
arr3

array([[[1, 2, 9],
        [3, 4, 9]],

       [[5, 6, 9],
        [7, 8, 9]]])

In [10]:
arr3.ndim

3

In [11]:
arr3.shape

(2, 2, 3)

In [12]:
arr3.size

12

In [13]:
arr3.dtype

dtype('int64')

int8 = 1 byte, int16 = 2 byte, int32 = 4 byte, int64 = 8 byte

In [14]:
float_array = np.array([1.5,2.7,3.1])

In [15]:
float_array.dtype

dtype('float64')

In [16]:
string_array = np.array(["Sanjay","Yalla"])

In [17]:
string_array.dtype # dtype of string array is <U6, which means Unicode string with maximum length of 6 characters.

dtype('<U6')

In [18]:
string_array.itemsize # itemsize gives the size in bytes of each element in the array. For a string array, it will depend on the maximum length of the strings in the array. In this case, since the maximum length is 6 characters, and each character is typically 4 bytes in Unicode, the itemsize will be 24 bytes (6 characters * 4 bytes per character).

24

In [19]:
one_d_zero_array = np.zeros(5) # 1D array of zeros
two_d_zero_array = np.zeros((3,4)) # 2D array of zeros
three_d_zero_array = np.zeros((2,3,4)) # 3D array of zeros

three_d_zero_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
one_d_ones_array = np.ones(5) # 1D array of ones
two_d_ones_array = np.ones((3,4)) # 2D array of ones
three_d_ones_array = np.ones((2,3,4)) # 3D array of ones
three_d_ones_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
full_array = np.full((1,2),8)
print(full_array)

[[8 8]]


In [22]:
np.empty((2,3)) # Create an empty array of shape (2,3). The values in the array will be uninitialized and may contain random data.

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [23]:
np.empty((2,3)) # Create an empty array of shape (2,3). The values in the array will be uninitialized and may contain random data.

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,10,5) # Create an array of 5 evenly spaced values between 0 and 10 (inclusive).

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr[0,2]

np.int64(3)

In [28]:
arr[:,(0,2)]

array([[1, 3],
       [4, 6]])

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.ndim

2

In [31]:
arr[:2] # Selects the first two rows of the array. The colon (:) indicates that we want all columns, and the 2 specifies that we want rows up to index 2 (not including index 2). So, it returns a new array containing the first two rows of the original array.

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr =  np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [33]:
arr.reshape(2,3) # Reshape the array to have 3 rows and 2 columns. The total number of elements must remain the same (6 in this case).

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
import time
start = time.time()
temp = []
for i in range(100000):
    temp.append(i)
end = time.time()
print(f"Time taken: {end - start}")
del temp

Time taken: 0.007719278335571289


In [35]:
import time
start = time.time()
arr = np.arange(100000)
end = time.time()
print(f"Time taken: {end - start}")

Time taken: 0.00028514862060546875


In [36]:
a = np.array([1,2,3,4,5])
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [38]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [39]:
arr <4

array([ True,  True,  True, False, False])

In [40]:
arr[arr < 4] # This line uses boolean indexing to select elements from the array arr that are less than 4. It creates a boolean mask (arr < 4) that evaluates to True for elements less than 4 and False otherwise. The resulting array will contain only the elements that satisfy this condition.

array([1, 2, 3])

In [42]:
A = np.array([
 [1,2],
 [3,4]
])

B = np.array([
 [5,6],
 [7,8]
])

In [43]:
A @ B

array([[19, 22],
       [43, 50]])

In [44]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [72]:
# Change just one value (e.g., 9 to 10) to break linear dependency
A= np.array([
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 10]
])


In [73]:
A.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [74]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [75]:
A.mT # matrix transpose

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [76]:
res1 = np.linalg.det(A) # Calculate the determinant of matrix A. The determinant is a scalar value that can be computed from the elements of a square matrix and provides important properties about the matrix, such as whether it is invertible. In this case, since A is not a square matrix (it has 2 rows and 3 columns), attempting to calculate its determinant will raise an error.
res1

np.float64(-2.9999999999999996)

In [78]:
res2 = np.linalg.inv(A) # Calculate the inverse of matrix A. The inverse of a square matrix A is another matrix, denoted as A^(-1), such that when multiplied with A, it yields the identity matrix. However, since A is not a square matrix (it has 2 rows and 3 columns), attempting to calculate its inverse will raise an error.
res2

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [83]:
A @ res2

array([[1.00000000e+00, 0.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [8.88178420e-16, 0.00000000e+00, 1.00000000e+00]])

In [2]:
import numpy as np

documents = np.array([
    [3, 4],
    [4, 3],
    [1, 0]
])

query = np.array([3.5, 3.5])

# Normalize documents
document_norms = np.linalg.norm(
    documents,
    axis=1,
    keepdims=True
)

In [3]:
document_norms

array([[5.],
       [5.],
       [1.]])

In [6]:
documents_normalized = documents / document_norms
documents_normalized

array([[0.6, 0.8],
       [0.8, 0.6],
       [1. , 0. ]])

In [8]:
query_normalized = query / np.linalg.norm(query)
query_normalized

array([0.70710678, 0.70710678])

In [11]:
scores = documents_normalized @ query_normalized
scores

array([0.98994949, 0.98994949, 0.70710678])

In [14]:
rankings = np.argsort(scores)[::-1]
rankings

array([0, 1, 2])

In [ ]:
def softmax(x: np.ndarray) -> np.ndarray:
    exp_x = np.exp(x - np.max(x))   # subtract max for numerical stability
    print("exp_x:", exp_x)
    return exp_x / np.sum(exp_x)

logits = np.array([11.0, 1999943.0, 0.1])
res= softmax(logits)   

In [ ]:
res